live_config_reload = true
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_padding = true
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 200
lines = 30

[window.padding]
x=5
y=5

[font]
size = 16 
normal = { family = "JetBrainsMono Nerd Font", style = "regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "italic" }

[env]
TERM = "xterm-256color"
