live_config_reload = true
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]


[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.95
[window.dimensions]
columns = 200
lines = 30
[window.padding]
x=5
y=5
[env]
TERM = "xterm-256color"
